export const RELEASE = Object.freeze({
  POTATO_COMMANDER_PUBLISHED: true,
  BUILD_LABEL: 'V2.0.0'
});

export const GAME = {
  WIDTH: 960,
  HEIGHT: 540,
  WORLD_WIDTH: 2200,
  WORLD_HEIGHT: 1400,
  PROTOTYPE_DURATION_SECONDS: 600
};


export const DIFFICULTY_PROFILES = Object.freeze({
  easy: Object.freeze({
    key: 'easy',
    label: '简单',
    description: '割草爽玩：怪更多但更脆、更慢，适合体验完整成长',
    playerMaxHpMultiplier: 1.22,
    contactInvulnMultiplier: 1.15,
    incomingDamageMultiplier: 0.85,
    minionHpMultiplier: 0.75,
    eliteHpMultiplier: 0.80,
    bossHpMultiplier: 0.85,
    minionSpeedMultiplier: 0.92,
    bossSpeedMultiplier: 0.97,
    spawnIntervalMultiplier: 0.95,
    eliteSpawnIntervalMultiplier: 1.33,
    xpNeedMultiplier: 0.90,
    bossActionCooldownMultiplier: 1.10,
    bossComboWeightMultiplier: 0.82,
    guardianDamageMultiplier: 1.10,
    supportHeartIntervalMultiplier: 1.00,
    supportHeartKillDropChance: 0.00
  }),
  normal: Object.freeze({
    key: 'normal',
    label: '普通',
    description: '标准节奏，当前所有 Boss 机制的基准难度',
    playerMaxHpMultiplier: 1,
    contactInvulnMultiplier: 1,
    incomingDamageMultiplier: 1,
    minionHpMultiplier: 1,
    bossHpMultiplier: 1,
    minionSpeedMultiplier: 1,
    bossSpeedMultiplier: 1,
    spawnIntervalMultiplier: 1,
    eliteSpawnIntervalMultiplier: 1,
    xpNeedMultiplier: 1,
    bossActionCooldownMultiplier: 1,
    bossComboWeightMultiplier: 1,
    guardianDamageMultiplier: 1,
    supportHeartIntervalMultiplier: 0.82,
    supportHeartKillDropChance: 0.025
  }),
  hard: Object.freeze({
    key: 'hard',
    label: '困难',
    description: '更高密度、更快推进与更高 Boss 组合技压力',
    playerMaxHpMultiplier: 0.90,
    contactInvulnMultiplier: 0.82,
    incomingDamageMultiplier: 1.25,
    minionHpMultiplier: 1.25,
    bossHpMultiplier: 1.28,
    minionSpeedMultiplier: 1.12,
    bossSpeedMultiplier: 1.10,
    spawnIntervalMultiplier: 0.82,
    eliteSpawnIntervalMultiplier: 0.80,
    xpNeedMultiplier: 1.12,
    bossActionCooldownMultiplier: 0.80,
    bossComboWeightMultiplier: 1.35,
    guardianDamageMultiplier: 0.88,
    supportHeartIntervalMultiplier: 0.68,
    supportHeartKillDropChance: 0.045
  })
});

export function getDifficultyProfile(key = 'normal') {
  return DIFFICULTY_PROFILES[key] ?? DIFFICULTY_PROFILES.normal;
}

export const PLAYER = {
  MAX_HP: 100,
  LEVEL_MAX_HP_GAIN: 2,
  SPEED: 230,
  ATTACK_DAMAGE: 12,
  FIRE_INTERVAL_MS: 500,
  BULLET_SPEED: 580,
  BULLET_LIFETIME_MS: 1300,

  MULTI_CRESCENT_TWO_DAMAGE_MULTIPLIER: 0.75,
  MULTI_CRESCENT_THREE_DAMAGE_MULTIPLIER: 0.60,
  MULTI_CRESCENT_TWO_SPREAD_DEG: 8,
  MULTI_CRESCENT_THREE_SPREAD_DEG: 12,
  MULTI_CRESCENT_SPAWN_OFFSET: 7,

  MOON_GUARD_RADIUS_X: 60,
  MOON_GUARD_FRONT_RADIUS_Y: 21,
  MOON_GUARD_BACK_RADIUS_Y: 9,
  MOON_GUARD_ANCHOR_Y_OFFSET: 9,
  MOON_GUARD_SPEED_RAD_PER_MS: 0.00455,
  MOON_GUARD_TRANSITION_SPEED_BOOST: 0.95,
  MOON_GUARD_HIDDEN_SPEED_BOOST: 0.28,
  MOON_GUARD_TRANSITION_SPEED_WIDTH_RAD: 0.26,
  MOON_GUARD_DAMAGE_MULTIPLIER: 0.40,
  MOON_GUARD_HIT_COOLDOWN_MS: 420,
  MOON_GUARD_HIT_RADIUS: 15,
  MOON_GUARD_KNOCKBACK: 118,
  MOON_GUARD_PNG_SIZE: 24,
  MOON_GUARD_PNG_ALPHA: 0.97,
  MOON_GUARD_BACK_ALPHA_FACTOR: 0.68,
  MOON_GUARD_BACK_SCALE: 0.84,
  MOON_GUARD_FRONT_SCALE: 1.04,
  MOON_GUARD_BODY_OCCLUSION_HALF_WIDTH: 27,
  MOON_GUARD_FRONT_DEPTH_OFFSET: 0.34,
  MOON_GUARD_BACK_DEPTH_OFFSET: -0.20,

  MOON_GUARD_PARTICLE_INTERVAL_MS: 28,
  MOON_GUARD_PARTICLE_COLOR: 0xff344d,
  MOON_GUARD_PARTICLE_HOT_COLOR: 0xff7682,
  MOON_GUARD_PARTICLE_MIN_RADIUS: 0.85,
  MOON_GUARD_PARTICLE_MAX_RADIUS: 1.55,
  MOON_GUARD_PARTICLE_MIN_LIFESPAN_MS: 120,
  MOON_GUARD_PARTICLE_MAX_LIFESPAN_MS: 185,
  CONTACT_INVULN_MS: 280,
  DASH_SPEED: 720,
  DASH_DURATION_MS: 175,
  DASH_COOLDOWN_MS: 3000,
  PERFECT_WINDOW_MS: 125,
  PERFECT_SHOCKWAVE_DAMAGE: 18,
  PERFECT_SHOCKWAVE_RADIUS: 120,
  SOUND_WAVE_DAMAGE: 0,
  SOUND_WAVE_KNOCKBACK: 0,
  SOUND_WAVE_RADIUS: 180,
  SOUND_WAVE_RADIUS_BY_LEVEL: Object.freeze([180, 195, 210, 225]),
  SOUND_WAVE_INTERVAL_MS: 6500,
  SOUND_WAVE_INTERVAL_MS_BY_LEVEL: Object.freeze([6500, 6000, 5500, 5000]),
  SOUND_WAVE_STUN_MS_BY_LEVEL: Object.freeze([800, 900, 1000, 1200]),
  SOUND_WAVE_ELITE_STUN_MULTIPLIER: 0.50,

  ELECTRIC_BURST_DAMAGE: 34,
  ELECTRIC_BURST_RADIUS: 230,
  ELECTRIC_STUN_MS: 520,
  ELECTRIC_SHOCK_DAMAGE: 16,
  ELECTRIC_SHOCK_RADIUS: 315,
  ELECTRIC_SHOCK_DELAY_MS: 150,
  ELECTRIC_SHOCK_KNOCKBACK: 430,
  ELECTRIC_INTERVAL_MS: 11500,

  STAGE_SPIN_DAMAGE: 12,
  STAGE_SPIN_RADIUS: 205,
  STAGE_SPIN_KNOCKBACK: 0,
  STAGE_SPIN_BASE_DISPLAY_SIZE: 160,
  STAGE_SPIN_DAMAGE_BY_COMBO_LEVEL: Object.freeze([6, 7, 8, 9, 10, 11, 12]),
  STAGE_SPIN_SIZE_GROWTH_START_COMBO: 40,
  STAGE_SPIN_SIZE_GROWTH_COMBO_STEP: 10,
  STAGE_SPIN_SIZE_GROWTH_PER_STEP: 0.05,
  STAGE_SPIN_SIZE_MAX_SCALE: 1.20,
  STAGE_SPIN_ALPHA_HIT_THRESHOLD: 20,

  KEY_UP_MAX: 100,
  KEY_UP_DAMAGE: 52,
  KEY_UP_RADIUS: 350,
  KEY_UP_KNOCKBACK: 520,

  SUPPORT_MAX: 100,
  SUPPORT_PER_HEART: 25,
  SUPPORT_HEAL_NORMAL: 4,
  SUPPORT_HEAL_LOW_HP: 8,
  SUPPORT_ACTIVE_HEAL: 18,
  SUPPORT_ACTIVE_DURATION_MS: 5000,
  SUPPORT_ACTIVE_EXTRA_REDUCTION: 0.28,
  SUPPORT_HEART_LIFETIME_MS: 14000,
  SUPPORT_HEART_FIRST_MS: 18000,
  SUPPORT_HEART_MIN_INTERVAL_MS: 19000,
  SUPPORT_HEART_MAX_INTERVAL_MS: 29000,
  SUPPORT_HEART_MIN_DISTANCE: 190,
  SUPPORT_HEART_MAX_DISTANCE: 300,

  BEAT_STRONG_WINDOW_MS: 75,
  BEAT_AUX_WINDOW_MS: 45,

  BEAT_CHARGE_DAMAGE_MULTIPLIER: 1.00,
  BEAT_CHARGE_SIZE_MULTIPLIER: 1.00,
  BEAT_CHARGE_COMBO_START: 9999,
  BEAT_CHARGE_COMBO_STEP: 9999,
  BEAT_CHARGE_COMBO_DAMAGE_STEP: 0.05,
  BEAT_CHARGE_COMBO_MAX_MULTIPLIER: 1.00,
  BEAT_CHARGE_EXTRA_KNOCKBACK: 0,
  BEAT_CHARGE_BOSS_EXTRA_KNOCKBACK: 0
};


export const ENEMIES = {
  potato: {
    hp: 44,
    speed: 78,
    damage: 7,
    contactDamageRange: [2, 4],
    defense: 0.28,
    knockbackScale: 0.30,
    xp: 1,
    contactCooldown: 700
  },
  duck: {
    hp: 20,
    speed: 108,
    damage: 6,
    contactDamageRange: [2, 3],
    defense: 0,
    xp: 1,
    contactCooldown: 560
  },
  ball: {
    hp: 22,
    speed: 245,
    damage: 10,
    contactDamageRange: [2, 5],
    xp: 2,
    contactCooldown: 700,
    lifetimeMinMs: 18000,
    lifetimeMaxMs: 24000
  },
  roach: {
    hp: 10,
    speed: 132,
    damage: 4,
    contactDamageRange: [1, 2],
    defense: 0,
    xp: 1,
    contactCooldown: 450,
    reproductionMinMs: 6000,
    reproductionMaxMs: 8500
  },
  twinPig: {
    hp: 155,
    speed: 38,
    damage: 9,
    xp: 5,
    contactCooldown: 760
  },
  plagueCat: {
    hp: 120,
    speed: 50,
    damage: 8,
    xp: 5,
    contactCooldown: 680
  },
  duckQueen: {
    hp: 660,
    armorHp: 440,
    speed: 102,
    damage: 0,
    defense: 0.18,
    xp: 20,
    contactCooldown: 900,

    gentleThreshold: 0.60,
    frenzyThreshold: 0.20,

    gentleSpeedMultiplier: 0.95,
    obsessedSpeedMultiplier: 1.28,
    frenzySpeedMultiplier: 1.48,

    attachDistance: 110,
    preferredDistance: 62,

    gentleStickTriggerRange: 155,
    obsessedStickTriggerRange: 195,
    frenzyStickTriggerRange: 235,
    gentleStickCooldownMs: 7000,
    obsessedStickCooldownMs: 4300,
    frenzyStickCooldownMs: 2700,
    gentleStickDashSpeed: 430,
    obsessedStickDashSpeed: 515,
    frenzyStickDashSpeed: 590,
    stickDashDurationMs: 560,

    grappleBreakInputs: 12,
    grappleDrainDamage: 2,
    grappleDrainHeal: 2,
    grappleDrainIntervalMs: 430,
    grappleQueenOffset: 56,
    grappleQueenVerticalOffset: 26,
    grappleBreakKnockback: 390,
    grappleReattachCooldownMs: 3500,
    grapplePostReleaseRoamMs: 1600,

    fishSkillDistance: 155,
    fishSkillCooldownMs: 8200,
    fishHomingSpeed: 360,
    fishNetBreakInputs: 3,
    fishNetPullSpeed: 220,

    charmGuaranteedHit: true,
    charmSkillCooldownMs: 6800,
    charmCastMs: 620,
    charmStatusDurationMs: 10000,
    charmInitialDazeMs: 650,

    majorActionInitialCooldownMs: 1600,
    singleActionWeight: 70,
    comboCharmFishWeight: 12,
    comboFishStickWeight: 13,
    comboCharmFishStickWeight: 5,
    comboStepGapMinMs: 850,
    comboStepGapMaxMs: 1250,
    singleActionCooldownMinMs: 2300,
    singleActionCooldownMaxMs: 3100,
    comboActionCooldownBaseMs: 2200,
    comboActionCooldownPerStepMs: 650,
    comboActionCooldownJitterMs: 450,

    ultimatePhaseEntryDelayMs: 5200,
    ultimateCooldownMinMs: 18000,
    ultimateCooldownMaxMs: 24000,
    ultimateRollChance: 0.18,
    ultimateRetryDelayMs: 2400,
    ultimateBlackframeHitCount: 3,
    ultimateBlackframeHitIntervalMs: 540,
    ultimateBlackframeImpactMs: 170,
    ultimateBlackframeAfterThirdMs: 360,
    ultimateBlackframeSlowPerHit: 0.20,
    ultimateTitleMs: 800,
    ultimateGroundDisplaySize: 520,
    ultimateImpaleGroundDisplaySize: 550,
    ultimateGroundOffsetY: 48,
    ultimateGroundFadeMs: 210,
    ultimateEvacRadiusX: 282,
    ultimateEvacRadiusY: 184,
    ultimateEvacSafePadding: 72,
    ultimateEvacSpeedMultiplier: 1.18,
    ultimateEvacRoachSpeedMultiplier: 1.62,
    ultimateEvacHoldSpeedMultiplier: 0.18,
    ultimateEvacWanderRadius: 24,
    ultimateEvacAngleJitterRad: 0.88,
    ultimateEvacFanStepRad: 0.18,
    ultimateEvacTargetJitterPx: 52,
    ultimateEvacSeparationRadius: 54,
    ultimateEvacSeparationWeight: 0.72,
    ultimateRoachChainExplosionMs: 380,
    ultimateRoachExplosionArmMs: 105,
    ultimateRoachEmptyBeatMs: 140,
    ultimateCloseupDisplayH: 505,
    ultimateCloseupPushInPx: 28,
    ultimateCloseupScreenX: 150,
    ultimateCloseupBottomY: 588,
    ultimateCloseupFeatherWidth: 540,
    ultimateCutsceneDisplaySize: 180,
    ultimateHangingDisplayScale: 1.15,
    ultimateFrameReliefMs: 420,
    ultimateFrameNoticeMs: 460,
    ultimateFramePanic1Ms: 500,
    ultimateFramePanic2Ms: 540,
    ultimateFrameTrappedMs: 620,
    ultimateFrameImpaledMs: 1200,
    ultimateFrameHangingMs: 1000,
    ultimateExplosionGrowMs: 220,
    ultimateExplosionBloomMs: 330,
    ultimateFlashInMs: 80,
    ultimateFlashHoldMs: 60,
    ultimateFlashOutMs: 320,
    ultimatePostRecoveryMs: 4500,
    ultimateDamageCurrentHpRatio: 0.55
  },
  potatoCommander: {
    skyBlueHp: 280,
    greenHp: 840,
    yellowHp: 840,
    hp: 840,
    speed: 80,
    damage: 12,
    defense: 0.25,
    xp: 20,
    contactCooldown: 760,

    crossAttackDamage: 5,
    crossAttackSpeed: 310,
    crossAttackCooldownMsByPhase: [1400, 1250, 1100, 950],
    crossAttackBurstCountByPhase: [1, 2, 3, 4],
    crossAttackBurstGapMs: 180,
    crossAttackLifetimeMs: 3000,
    crossAttackExplosionDurationMs: 260,


    groupIntervalMs: 6800,
    groupTargets: 7,
    groupBuffMs: 4700,
    groupCircleIntroMs: 180,
    groupSpawnStaggerMs: 90,
    groupRiseMs: 380,
    groupHopMs: 260,
    groupCastArtMs: 1650,
    groupSpawnRadiusX: 118,
    groupSpawnRadiusY: 58,
    commanderGroupTriggerPopulation: 15,
    commanderTargetPotatoPopulation: 18,
    commanderPopulationCheckMs: 350,
    commanderEmergencyGroupCooldownMs: 3600,
    commanderFollowerMin: 4,
    commanderFollowerDesired: 5,
    commanderFollowerMax: 6,
    commanderFollowerRadiusX: 168,
    commanderFollowerRadiusY: 104,
    commanderFollowerYOffset: 18,
    commanderFollowerOrbitSpeed: 0.00011,
    commanderFollowerMoveSpeedMultiplier: 0.72,
    commanderGraceComboWindowMs: 5600,

    skySmashIntervalMs: 6200,
    skySmashWarningMs: 760,
    skySmashRadius: 102,
    skySmashDamage: 8,
    skySmashStunFrameMsByPhase: [1500, 1500, 1500],
    skySmashRecoveryFrameMsByPhase: [500, 500, 500],
    skySmashSlideDistanceByPhase: [56, 64, 72],
    skySmashSlideDurationMsByPhase: [120, 140, 160],
    skySmashClearanceMargin: 16,
    skySmashHitFlashMsByPhase: [120, 140, 160],
    skySmashLandingHoldMsByPhase: [650, 750, 900],


    likeIntervalMs: 6600,
    likeCastArtMs: 1320,
    likeThumbCount: 3,
    likeThumbGapMs: 185,
    likeThumbWarningMs: 105,
    likeThumbRiseMs: 170,
    likeThumbHoldMs: 90,
    likeThumbFadeMs: 170,
    likePredictMs: 110,
    likeHitRadius: 44,
    likeDamage: 7,
    likeLaunchHeight: 78,
    likeLaunchRiseMs: 165,
    likeLaunchFallMs: 205,
    likeLandingStunMs: 280,

    holyIntervalMs: 8200,
    holyCastMs: 1900,
    holyRadius: 420,
    holyTargets: 7,
    holyPulseTimesMs: [360, 820, 1280],
    holyBeamFadeMs: 260,
    holyReleaseMs: 1600,

    holySelfDestructArmMs: 340,
    holySelfDestructBlinkMs: 92,
    holySelfDestructSpeed: 272,
    holySelfDestructTriggerRadius: 52,
    holySelfDestructBlastRadius: 108,
    holySelfDestructDamage: 10,
    holySelfDestructMaxChaseMs: 5200,
    holySelfDestructShakeMs: 145,
    holySelfDestructShakeIntensity: 0.0135,

    comboStepGapMinMs: 760,
    comboStepGapMaxMs: 1080,
    comboActionCooldownBaseMs: 2200,
    comboActionCooldownPerStepMs: 620,
    comboActionCooldownJitterMs: 520,
    singleActionCooldownMinMs: 4100,
    singleActionCooldownMaxMs: 5600,
    singleActionWeight: 68,
    comboGroupSmashWeight: 14,
    comboGroupHolyWeight: 14,
    comboGroupCleanseWeight: 12,
    comboCleanseHolyWeight: 13,
    comboLikeHolyWeight: 12,
    comboSmashHolyWeight: 11,
    comboHolyCrossWeight: 10,
    comboGroupAbsorbWeight: 12,
    comboAbsorbSmashWeight: 10,
    comboGroupCleanseHolyWeight: 5,
    comboCrossVolleyGapMs: 135,

    cleanseRadius: 520,
    cleanseTargets: 6,
    cleanseMinTargets: 3,
    cleanseCastMs: 1320,
    cleanseSweepMs: 280,
    cleanseLaunchDelayMs: 125,
    cleanseLaunchStaggerMs: 62,
    cleanseFlightMsMin: 430,
    cleanseFlightMsMax: 590,
    cleanseLandingRadiusMin: 58,
    cleanseLandingRadiusMax: 108,
    cleanseIntervalMs: 6400,
    cleanseComboWindowMs: 7600,
    cleanseComboNextActionMinMs: 2500,
    cleanseComboNextActionMaxMs: 3200,

    absorbIntervalMs: 7600,
    absorbCount: 6,
    absorbRadius: 520,
    absorbDurationMs: 2400,
    absorbPulseTimesMs: [420, 900, 1380, 1860],
    absorbFinishMs: 2260,
    absorbFaithValueByGrowth: [1, 1.5, 2, 3],
    absorbHealRatioPerFaith: 0.015,
    absorbHealCapRatioPerCast: 0.14,
    absorbShieldRatioPerFaith: 0.01,
    absorbShieldCapRatio: 0.10,
    absorbJudgmentChargeCap: 18,
    absorbAuraYOffset: 48,
    absorbStreamIntervalMs: 54,
    absorbStreamMotesPerTick: 5,
    absorbPulseBurstMotes: 10,

    judgmentGraceCastsRequired: 3,
    judgmentIntroMs: 760,
    judgmentRainCounts: [8, 18, 42],
    judgmentRainIntervalsMs: [280, 115, 62],
    judgmentRainFallMs: [440, 325, 245],
    judgmentRainTelegraphMs: [280, 220, 255],
    judgmentPlayerAimChance: [0.01, 0.03, 0.06],
    judgmentPlayerSurroundChance: [0.58, 0.50, 0.36],
    judgmentPlayerPredictChance: [0.18, 0.40, 0.52],
    judgmentSurroundRadiusMin: [54, 42, 28],
    judgmentSurroundRadiusMax: [112, 88, 60],
    judgmentRainFinalDelayMs: 430,
    judgmentPanicLeadMs: 1120,
    judgmentAfterimageMs: 680,
    judgmentDamageCurrentHpRatio: 0.60,
    judgmentHeadHitDamageMin: 2,
    judgmentHeadHitDamageMax: 8,
    judgmentPostHoldMs: 1040,
    judgmentSpawnBreatherMs: 1500,

    blackwaterPreludePauseMs: 520,
    blackwaterCloseupFeatherWidth: 540,
    blackwaterRainStartMs: 1450,
    blackwaterPostHoldMs: 1450,
    blackwaterFinalBombardmentVisibleMs: 380,
    blackwaterFinalBombardmentVisibleMsV116: 520,
    blackwaterFinalEndingRevealDelayMs: 540,
    blackwaterFinalEndingHoldMs: 1050,
    blackwaterFinalWhiteInMs: 150,
    blackwaterFinalWhiteHoldMs: 420,
    blackwaterFinalWhiteOutMs: 760,
    blackwaterFinalShakeMs: 1120,
    blackwaterFinalShakeStrength: 0.040,
    blackwaterFinalShakeStrengthV116: 0.055,
    blackwaterTitleHoldMsV123: 900,
    blackwaterFinalBombardmentVisibleMsV123: 300,
    blackwaterFinalEndingRevealDelayMsV123: 0,
    blackwaterFinalEndingHoldMsV123: 0,
    blackwaterFinalWhiteInMsV123: 90,
    blackwaterFinalWhiteHoldMsV123: 900,
    blackwaterFinalWhiteOutMsV123: 1100,
    blackwaterTitleHoldMsV124: 850,
    blackwaterFinalBombardmentVisibleMsV124: 300,
    blackwaterFinalWhiteInMsV124: 100,
    blackwaterFinalWhiteHoldMsV124: 900,
    blackwaterFinalWhiteOutMsV124: 1150,
    blackwaterFinalBombardmentVisibleMsV125: 80,
    blackwaterFinalWhiteInMsV125: 55,
    blackwaterFinalWhiteHoldMsV125: 1250,
    blackwaterFinalWhiteOutMsV125: 1100,
    blackwaterFinalShakeStrengthV125: 0.052,
    blackwaterFinalBombardmentVisibleMsV126: 260,
    blackwaterFinalWhiteInMsV126: 90,
    blackwaterFinalWhiteHoldMsV126: 1300,
    blackwaterFinalWhiteOutMsV126: 1100,
    blackwaterFinalShakeStrengthV126: 0.050,
    blackwaterFinalBombardmentVisibleMsV127: 460,
    blackwaterFinalWhiteInMsV127: 45,
    blackwaterFinalWhiteHoldMsV127: 650,
    blackwaterFinalWhiteOutMsV127: 550,
    blackwaterCraterPersistMs: 30000,
    blackwaterFinalDamageMaxHpRatio: 0.60,

    worshipShieldPerDuck: 0.04,
    worshipShieldCap: 0.34
  }
};

export const SPAWN = {
  BASE_INTERVAL_MS: 790,
  MIN_INTERVAL_MS: 240,
  MAX_ALIVE: 165,

  VISIBLE_TARGET_POINTS: [
    [0, 15],
    [60, 22],
    [120, 30],
    [180, 38],
    [240, 45],
    [300, 50]
  ],
  VISIBLE_REFILL_MARGIN: 4,
  VISIBLE_SOFT_MARGIN: 2,
  VISIBLE_HARD_CAP: 60,
  VISIBLE_REFILL_INTERVAL_START_MS: 980,
  VISIBLE_REFILL_INTERVAL_END_MS: 360,
  VISIBLE_REFILL_BATCH_MID_SECONDS: 120,
  VISIBLE_REFILL_BATCH_LATE_SECONDS: 240,
  MAX_BALLS: 5,
  MAX_ROACHES: 70,
  ROACH_START_SECONDS: 30,
  POTATO_START_SECONDS: 60,
  BALL_START_SECONDS: 90,
  BALL_VOLLEY_DOUBLE_START_SECONDS: 180,
  BALL_VOLLEY_TRIPLE_START_SECONDS: 300,
  BALL_VOLLEY_SHOT_INTERVAL_MS: 1000,
  BALL_SPEED_RAMP_START_SECONDS: 150,
  MID_COMMON_MIX_START_SECONDS: 150,

  EARLY_ROACH_PAIR_SECONDS: 30,
  EARLY_WAVE_SECONDS: 45,
  EARLY_POTATO_INTRO_SECONDS: 60,
  TWIN_PIG_START_SECONDS: 105,
  PLAGUE_CAT_START_SECONDS: 165,
  MAX_TWIN_PIGS: 2,
  MAX_PLAGUE_CATS: 2,
  DUCK_QUEEN_SPAWN_SECONDS: 300,
  POTATO_COMMANDER_SPAWN_SECONDS: 540,
  SPAWN_DISTANCE_MIN: 500,
  SPAWN_DISTANCE_MAX: 720,

  POTATO_PRESSURE_PER_ALIVE: 0.06,
  POTATO_PRESSURE_CAP: 0.24,

  DUCK_QUACK_MIN_INTERVAL_MS: 2500,
  DUCK_QUACK_MAX_INTERVAL_MS: 5000,
  DUCK_QUACK_MAX_VISIBLE: 4
};

export const XP = {
  BASE_TO_LEVEL: 5,
  PER_LEVEL: 4,
  PICKUP_RADIUS: 34
};


export const STATUS_EFFECTS = {
  plagueSpeedMultiplier: 1.20,
  plagueDurationMs: 14500,
  plagueSpreadRadius: 120,
  plagueZoneDurationMs: 6000,
  plagueZoneRadius: 95,
  poopDurationMs: 12500,
  poopProjectileDamage: 5,
  poopProjectileSpeed: 285,
  poopProjectileLifetimeMs: 3600,

  jealousDurationMs: 1400,
  jealousAttackSpeedMultiplier: 1.10,
  jealousSpeedMultiplier: 1.30,
  sugarHighDurationMs: 1400,
  sugarHighDamageMultiplier: 1.25,
  sugarHighSpeedMultiplier: 1.25,
  sugarHighReproductionIntervalMultiplier: 0.55,

  fishNetPullSpeed: 220,

  fishSmallDamage: 4,
  fishSmallSpeed: 350,
  fishSmallSlowMultiplier: 0.90,
  fishSmallSlowMs: 700,

  fishBigDamage: 8,
  fishBigSpeed: 235,
  fishBigSlowMultiplier: 0.78,
  fishBigSlowMs: 1150,

  fishStinkyDamage: 5,
  fishStinkySpeed: 275,
  fishStinkySlowMultiplier: 0.84,
  fishStinkySlowMs: 950,
  fishStinkZoneRadius: 72,
  fishStinkZoneDurationMs: 1900,
  fishStinkZoneSlowMultiplier: 0.72,

  fishProjectileLifetimeMs: 3600,

  blessedToxicPoisonDurationMs: 15000,
  blessedToxicPoisonTickMs: 500,
  blessedToxicPoisonDamage: 1
};
